### ISSUE TITLE
Error npm install

### ISSUE THREAD

**Issue by njamortel** [SOCR/SOCRAT-issues#304]
i’m working with this repository (https://github.com/SOCR/SOCRAT.git) apparently whenever i use the latest stable version, npm install but won’t start and it works in mac environment. I want to try in windows 10 64 bit

**Comment by alxndrkalinin** [comment]
@njamortel what error do you get?

**Comment by njamortel** [comment]
I got this error and can't run npm server. :(

20 error code ELIFECYCLE

21 error errno 1

22 error SOCRAT@0.1.9 serve:
`node_modules/webpack-dev-server/bin/webpack-dev-server.js --hot --inline
--colors --content-base _build/ --host 127.0.0.1 --port 8080`

22 error Exit status 1

23 error Failed at the SOCRAT@0.1.9 serve script.

23 error This is probably not a problem with npm. There is likely
additional logging output above.

24 verbose exit [ 1, true ]


[image: image.png]

May I know what version of node will support for SOCRAT?

Do I need C++ build too?

Thank you.

**Comment by njamortel** [comment]
here's the debug log:

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'serve'
1 verbose cli ]
2 info using npm@6.12.1
3 info using node@v12.13.1
4 verbose run-script [ 'preserve', 'serve', 'postserve' ]
5 info lifecycle SOCRAT@0.2.0~preserve: SOCRAT@0.2.0
6 info lifecycle SOCRAT@0.2.0~serve: SOCRAT@0.2.0
7 verbose lifecycle SOCRAT@0.2.0~serve: unsafe-perm in lifecycle true
8 verbose lifecycle SOCRAT@0.2.0~serve: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\OneDrive - PLDT\NetDevOps\Dev_Staging\Data-Science\SOCRAT\node_modules\.bin;C:\Python27\;C:\Python27\Scripts;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files;C:\Winnt;C:\Winnt\System32;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\Program Files\Git LFS;C:\Program Files\Redis\;C:\Program Files\dotnet\;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\cl.exe;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;D:\OneDrive - PLDT\NetDevOps\xampp\mysql\bin;C:\Windows\System32\wbem;C:\Program Files\nodejs\;C:\Users\namortel\AppData\Local\Programs\Python\Python37\Scripts\;C:\Users\namortel\AppData\Local\Programs\Python\Python37\;C:\Program Files\Git\bin;C:\Program Files\Java\jdk-11.0.2/bin;C:\Users\namortel\AppData\Local\Microsoft\WindowsApps;D:\OneDrive - PLDT\DevOps\xampp\mysql\bin;C:\Users\namortel\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\namortel\AppData\Roaming\npm
9 verbose lifecycle SOCRAT@0.2.0~serve: CWD: D:\OneDrive - PLDT\NetDevOps\Dev_Staging\Data-Science\SOCRAT
10 silly lifecycle SOCRAT@0.2.0~serve: Args: [
10 silly lifecycle   '/d /s /c',
10 silly lifecycle   'node_modules/webpack-dev-server/bin/webpack-dev-server.js --hot --inline --colors --content-base _build/ --host 127.0.0.1 --port 8080'
10 silly lifecycle ]
11 silly lifecycle SOCRAT@0.2.0~serve: Returned: code: 1  signal: null
12 info lifecycle SOCRAT@0.2.0~serve: Failed to exec serve script
13 verbose stack Error: SOCRAT@0.2.0 serve: `node_modules/webpack-dev-server/bin/webpack-dev-server.js --hot --inline --colors --content-base _build/ --host 127.0.0.1 --port 8080`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:210:5)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:210:5)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid SOCRAT@0.2.0
15 verbose cwd D:\OneDrive - PLDT\NetDevOps\Dev_Staging\Data-Science\SOCRAT
16 verbose Windows_NT 10.0.16299
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "serve"
18 verbose node v12.13.1
19 verbose npm  v6.12.1
20 error code ELIFECYCLE
21 error errno 1
22 error SOCRAT@0.2.0 serve: `node_modules/webpack-dev-server/bin/webpack-dev-server.js --hot --inline --colors --content-base _build/ --host 127.0.0.1 --port 8080`
22 error Exit status 1
23 error Failed at the SOCRAT@0.2.0 serve script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
